"""empty message

Revision ID: 344d50dbfef5
Revises: 8d7de732a034
Create Date: 2024-09-22 12:10:21.478682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '344d50dbfef5'
down_revision = '8d7de732a034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.drop_column('quanity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quanity', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
