"""implement new features

Revision ID: 9e390b38c47d
Revises: 
Create Date: 2024-09-21 08:45:25.919484

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e390b38c47d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('id')
        batch_op.drop_index('password')

    op.drop_table('users')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_status', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('customer_id', sa.String(length=60), nullable=False))
        batch_op.drop_constraint('orders_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('paid')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.VARCHAR(length=60), nullable=False))
        batch_op.add_column(sa.Column('paid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('orders_ibfk_1', 'users', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')
        batch_op.drop_column('payment_status')

    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('password', ['password'], unique=True)
        batch_op.create_index('id', ['id'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    # ### end Alembic commands ###
